name: Deploy Tesla PEM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy PEM to output folder
        run: |
          mkdir -p out/.well-known/appspecific
          cp .well-known/appspecific/com.tesla.3p.public-key.pem out/.well-known/appspecific/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
